/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // Tono papel / rojo profundo de la decoración del promo
        paper: "#f6efe9",
        "paper-deep": "#efe4dc",
        wine: "#8c1128",
        "wine-deep": "#5e0a1b",
        blush: "#f3d8d8",
        "primary-fixed": "#ffdadb",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#dac0c2",
        "tertiary-fixed": "#ffdadc",
        tertiary: "#a63047",
        "surface-variant": "#f9dcdc",
        "surface-container-low": "#fff0f0",
        "surface-container-highest": "#f9dcdc",
        "tertiary-container": "#c6495e",
        "surface-container": "#ffe9e9",
        primary: "#b90538",
        "on-background": "#271718",
        "surface-dim": "#f0d3d4",
        "surface-bright": "#fff8f7",
        "secondary-container": "#f7dcde",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb2b9",
        "inverse-surface": "#3e2c2d",
        "on-primary-fixed-variant": "#92002a",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#40000d",
        "on-secondary-container": "#735f61",
        "surface-tint": "#bc0b3b",
        "on-tertiary-fixed-variant": "#891933",
        surface: "#fff8f7",
        "inverse-on-surface": "#ffecec",
        "error-container": "#ffdad6",
        "primary-container": "#dc2c4f",
        "secondary-fixed": "#f7dcde",
        "inverse-primary": "#ffb2b7",
        background: "#fff8f7",
        secondary: "#6d5a5b",
        "surface-container-high": "#ffe1e2",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-surface": "#271718",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        outline: "#8f6f71",
        "on-secondary-fixed-variant": "#544244",
        "on-surface-variant": "#5b4041",
        "outline-variant": "#e3bdbf",
        "on-secondary-fixed": "#26181a",
        "on-tertiary-container": "#fffbff",
        "primary-fixed-dim": "#ffb2b7",
        "on-primary-container": "#fffbff",
        "on-tertiary-fixed": "#400010",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        "stack-lg": "32px",
        "container-max": "1200px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        gutter: "24px",
        "stack-md": "16px",
        "section-gap": "80px",
      },
      fontFamily: {
        script: ['"Great Vibes"', '"Playfair Display"', "cursive"],
        "label-md": ['"Be Vietnam Pro"', "sans-serif"],
        "headline-sm": ['"Playfair Display"', "serif"],
        "body-lg": ['"Be Vietnam Pro"', "sans-serif"],
        "body-md": ['"Be Vietnam Pro"', "sans-serif"],
        "headline-md": ['"Playfair Display"', "serif"],
        "display-lg-mobile": ['"Playfair Display"', "serif"],
        "display-lg": ['"Playfair Display"', "serif"],
        "label-sm": ['"Be Vietnam Pro"', "sans-serif"],
        "display-sm": ['"Playfair Display"', "serif"],
        "title-lg": ['"Be Vietnam Pro"', "sans-serif"],
      },
    },
  },
  plugins: [],
};